services:

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=all_account
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI

volumes:
    postgres_data:
