# Generated by Django 5.0.6 on 2024-06-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit', models.CharField(max_length=70, verbose_name='Credit')),
                ('debit', models.CharField(max_length=70, verbose_name='Debit')),
                ('opening_balance', models.CharField(max_length=70, verbose_name='Opening Balance')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='shop.shop')),
            ],
            options={
                'verbose_name': 'Lager',
                'verbose_name_plural': 'Lagers',
                'ordering': ['-id'],
            },
        ),
    ]
